spring.application.name=SpringEcomWebApp

spring.datasource.url=jdbc:postgresql://localhost:5432/Star
#spring.datasource.password=
spring.datasource.username=hardivirani

spring.jpa.hibernate.ddl-auto=update

#This basically helps request the server of every letter you type. This is vague explanatio, can see the video again which is vid-112 or ask AI.
spring.datasource.hikari.auto-commit=false
